services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge

